example.property: "I AM A DEV PROPERTY OVERRIDE"


## JPA
spring.jpa.generate-ddl: "true"
spring.jpa.hibernate.ddl-auto: "update"
spring.jpa.show-sql: "true"


## H2
spring.h2.console.enabled: "true"


## SECURITY
security:
  oauth2:
    resource:
      user-info-uri: http://localhost:8901/auth/user/
    client:
      grant-type: client_credentials

## REDIS
spring:
  redis:
    port: 6379
    host: localhost
    
